plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/kgosschalk/Documents/SUI/PS1/games/Wild Arms 2/wiki_deploy"
publishOrigin = "default"
base = "/Users/kgosschalk/Documents/SUI/PS1/games/Wild Arms 2/wiki_deploy"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]