// WA2 Japanese decoder + EN<->JP aligner — JS port of tools/wa2_jp_decode.py and the
// jp_boxes/align halves of tools/extract_boxes.py. Held to parity with the Python originals
// by web/tests/jp.test.mjs (golden fixture regenerated by web/gen_tables.py).
// Tables (kanji map, per-block local tables, F0/DTE, katakana) load from data/jp_tables.json.
(function (root) {
  "use strict";
  const SJIS = new TextDecoder("shift_jis");
  const JBLK = 110592;

  // WHATWG TextDecoder uses the CP932 variants for a few JIS X 0208 codepoints; CPython's
  // shift_jis uses the strict JIS mappings. Post-map so JS output == the python tools.
  const CP932_FIX = { "\uff5e": "\u301c", "\u2225": "\u2016", "\uff0d": "\u2212",
                      "\uffe0": "\u00a2", "\uffe1": "\u00a3", "\uffe2": "\u00ac" };
  const sjisFix = (s) => s.replace(/[\uff5e\u2225\uff0d\uffe0\uffe1\uffe2]/g, (c) => CP932_FIX[c]);

  let T = null;            // {kanji, blocks, f0, kata}
  const HIRA = {};         // single-byte 0x28.. -> SJIS hiragana block glyphs 0x829f..0x82f1
  for (let lo = 0x9f, k = 0; lo <= 0xf1; lo++, k++) HIRA[0x28 + k] = SJIS.decode(new Uint8Array([0x82, lo]));

  function init(tables) {
    T = { kanji: tables.kanji, blocks: tables.blocks, f0: tables.f0, kata: {} };
    for (const [h, g] of Object.entries(tables.kata)) T.kata[parseInt(h, 16)] = g;
  }
  const hex2 = (b) => b.toString(16).padStart(2, "0");

  // ---- decode(): the global (block-agnostic) decoder -------------------------
  function decode(b) {
    const out = []; let i = 0;
    while (i < b.length) {
      const c = b[i];
      if (c === 0x00) break;
      if (c === 0xf0 && i + 1 < b.length) {
        out.push(T.f0[hex2(b[i + 1])] ?? `<f0${hex2(b[i + 1])}>`); i += 2; continue;
      }
      if (((c >= 0x81 && c <= 0x9f) || (c >= 0xe0 && c <= 0xef)) && i + 1 < b.length) {
        const h = hex2(c) + hex2(b[i + 1]);
        if (T.kanji[h]) { out.push(T.kanji[h]); i += 2; continue; }
        if ((c === 0x88 || c === 0x89 || c === 0x8a) && h !== "8140") { out.push(`<${h}>`); i += 2; continue; }
        // CPython's shift_jis rejects leads 0xeb-0xef (IBM/NEC extension area); WHATWG maps
        // some of them. Match CPython so JS output stays identical to the tools.
        let s = null;
        if (c <= 0x9f || c <= 0xea) { try { s = SJIS.decode(new Uint8Array([c, b[i + 1]])); } catch (e) { s = null; } }
        out.push(s && !s.includes("�") ? sjisFix(s) : `<${h}>`);
        i += 2; continue;
      }
      if (HIRA[c] !== undefined) { out.push(HIRA[c]); i++; continue; }
      if (T.kata[c] !== undefined) { out.push(T.kata[c]); i++; continue; }
      if (c === 0x0d) { out.push("\n"); i++; continue; }
      if (c >= 0x20 && c < 0x7f) { out.push(String.fromCharCode(c)); i++; continue; }
      out.push(`[${hex2(c)}]`); i++;
    }
    return out.join("");
  }

  // ---- decode_block(): two-tier (global < 0x8a38, block-local >= 0x8a38) -----
  const KHI = new Set([0x88, 0x89, 0x8a, 0x8b]);
  const TWO = new Set([0xf0, 0x05, 0x0a, 0x0b, 0x10, 0x11, 0x13, 0x16, 0x17, 0x18]);
  function decodeBlock(data, block) {
    const bt = T.blocks[String(block)] || {};
    const out = []; let j = 0; const n = data.length;
    while (j < n) {
      const c = data[j];
      if (KHI.has(c) && j + 1 < n) {
        const code = (c << 8) | data[j + 1];
        if (code >= 0x8a38) {
          const h = code.toString(16).padStart(4, "0");
          out.push(bt[h] ?? `<b:${h}>`); j += 2; continue;
        }
      }
      let k = j;
      while (k < n) {
        const cc = data[k];
        if (KHI.has(cc) && k + 1 < n && (((cc << 8) | data[k + 1]) >= 0x8a38)) break;
        if (KHI.has(cc) && k + 1 < n) k += 2;
        else if (TWO.has(cc) && k + 1 < n) k += 2;
        else k += 1;
      }
      out.push(decode(data.subarray(j, k)));
      j = k;
    }
    return out.join("");
  }

  // ---- jp_boxes(): the JP half of extract_boxes._extract ---------------------
  const isJpLead = (b) => (b >= 0x81 && b <= 0x9f) || (b >= 0xe0 && b <= 0xef);
  const sq = (s) => s.split(/\s+/).filter(Boolean).join(" ");
  function jpBoxes(jd, blk) {
    const lo = blk * JBLK, hi = Math.min((blk + 1) * JBLK, jd.length);
    const out = []; let i = lo;
    while (i < hi - 1) {
      const b = jd[i]; let frame = null;
      let fi = i;
      if (b === 0x10 && jd[i + 1] === 0x0c) { frame = "idx"; fi = i + 1; }
      else if (b === 0x06) frame = "inline";
      else if (b === 0x0d) frame = "cont";
      if (frame) {
        const s = fi + 1;
        if (s >= hi) { i++; continue; }
        let k = s; while (k < hi && jd[k] !== 0x00) k++;
        const chunk = jd.subarray(s, k);
        // split on \x10\x0c
        const subs = []; let last = 0;
        for (let p = 0; p + 1 < chunk.length; p++)
          if (chunk[p] === 0x10 && chunk[p + 1] === 0x0c) { subs.push(chunk.subarray(last, p)); last = p + 2; p++; }
        subs.push(chunk.subarray(last));
        let emitted = false, nsub = 0;
        for (const sub of subs) {
          if (!sub.length) continue;
          if (!isJpLead(sub[0])) continue;
          const t = sq(decodeBlock(sub, blk).replace(/\n/g, " "));
          let cjk = 0, kana = 0;
          for (const ch of t) {
            const cp = ch.codePointAt(0);
            if ((cp >= 0x3040 && cp <= 0x30ff) || (cp >= 0x4e00 && cp <= 0x9fff)) cjk++;
            if (cp >= 0x3040 && cp <= 0x30ff) kana++;
          }
          if (cjk >= 2 || kana >= 3) {
            const panel = t.replace(/^[「『 ]+/, "").startsWith("＊");
            out.push({ off: fi - (frame === "idx" ? 1 : 0), sub: nsub, text: t, indexed: frame === "idx", panel });
            nsub++; emitted = true;
          }
        }
        if (emitted && k > s) { i = k; continue; }
      }
      i++;
    }
    return out;
  }

  // ---- align(): monotonic DP, EN authoritative (port of extract_boxes.align) --
  const digits = (s) => ((s || "").normalize("NFKC").match(/\d/g) || []).join("");
  function pairScore(en, jp) {
    const de = digits(en), dj = digits(jp);
    if (de && dj && de === dj && de.length >= 2) return 3.0;
    const le = en.length, lj = jp.length;
    if (le < 2 || lj < 2) return 0.0;
    return Math.max(0, 1 - Math.abs(le / lj - 1.7) / 2.5) * 0.4;
  }
  function align(enb, jpb, diag = 1.0, gap = -0.05) {
    const enS = enb.filter((b) => !b.panel).map((b) => b.text);
    const jpS = jpb.filter((b) => !b.panel).map((b) => b.text);
    const n = enS.length, m = jpS.length, NEG = -1e9;
    const dp = Array.from({ length: n + 1 }, () => new Float64Array(m + 1).fill(NEG));
    const bt = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(null));
    dp[0][0] = 0;
    for (let i = 0; i <= n; i++) for (let j = 0; j <= m; j++) {
      const c = dp[i][j];
      if (c === NEG && (i || j)) continue;
      if (i < n && j < m) {
        const v = c + pairScore(enS[i], jpS[j]) + diag * (1 - Math.abs(i / Math.max(n, 1) - j / Math.max(m, 1)));
        if (v > dp[i + 1][j + 1]) { dp[i + 1][j + 1] = v; bt[i + 1][j + 1] = [i, j]; }
      }
      if (i < n && c + gap > dp[i + 1][j]) { dp[i + 1][j] = c + gap; bt[i + 1][j] = [i, j]; }
      if (j < m && c + gap > dp[i][j + 1]) { dp[i][j + 1] = c + gap; bt[i][j + 1] = [i, j]; }
    }
    const mp = new Map(); let i = n, j = m;
    while (i !== 0 || j !== 0) {
      const [pi, pj] = bt[i][j];
      if (pi === i - 1 && pj === j - 1) mp.set(i - 1, j - 1);
      i = pi; j = pj;
    }
    const pairs = [];
    for (let x = 0; x < n; x++) {
      const jj = mp.has(x) ? mp.get(x) : null;
      const jt = jj !== null ? jpS[jj] : "";
      let conf = "";
      if (jj !== null) {
        const de = digits(enS[x]);
        conf = de && de === digits(jt) && de.length >= 2 ? "anchor" : "approx";
      }
      pairs.push({ i: x, en: enS[x], jp: jt, conf });
    }
    return { pairs, n, m };
  }

  const api = { init, decode, decodeBlock, jpBoxes, align, JBLK };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.WA2JP = api;
})(typeof globalThis !== "undefined" ? globalThis : this);
